#!/bin/bash
#SBATCH --time=00:15:00
#SBATCH --account=an-tr043
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=4GB
#SBATCH --output=ISP-%j.out


#add  module
module load python/3.11.5

virtualenv --no-download $SLURM_TMPDIR/env
source $SLURM_TMPDIR/env/bin/activate
pip install --no-index --upgrade pip
pip install --no-index pandas numpy matplotlib seaborn scikit-learn



#python scripts
python Homicide_Prediction_ISP.py

